import './globals.css'
import { Roboto, Noto_Sans_KR } from 'next/font/google'


const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ["latin"], // 또는 preload: false
  weight: ["100", "400", "700", "900"], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

const roboto = Roboto({
  subsets: ["latin"], // preload에 사용할 subsets입니다.
  weight: ["100", "400", "700"],
  variable: "--roboto", // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <div className="flex min-h-screen max-lg:justify-center">
          <div className="fixed left-[calc(50vw_-_551px)] w-full h-full max-w-[500px] bg-slate-50 max-lg:hidden">
            왼쪽메뉴화면
          </div>
          <div className="relative overflow-hidden w-full max-w-[420px] lg:ml-[calc(50vw_-_1px)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
